node22, upgrade dependencies
alchemix-finance/srens-web pull request #2
Opened 2024-11-07 05:28 UTC by aquaticone

### Changes

- upgraded node version to 22 LTS
- upgraded all dependencies to latest (exceptions below)
- refactored contract interactions as needed to retain existing functionality with underlying library changes
- added env var `NEXT_PUBLIC_WALLETCONNECT_PROJECT_ID` -- [create one here for the app to work](https://cloud.reown.com/app)

#### Version Exceptions

- `@graphprotocol/client-cli`, `@headlessui/react`, `@headlessui/tailwindcss` unchanged because they work
- `next` upgraded to v14 (with default `eslint` versions and config)

### Notes

#### Testing

Tested and working against prod. 

#### The Graph

The graph changed their policies since this app was written originally. I ran into some issues with CORS locally which I was able to resolve with a Next.js rewrites proxy; I think this should be fine without a proxy in prod but I'm not 100% sure. They also have pretty insane rate limiting in place without an API key. No changes there in this PR, but an API key might be needed if there are issues in prod.

2024-11-08 20:40 UTC, t0rbik requested changes

2024-11-08 20:40 UTC, t0rbik commented on package.json
> +  }
can you remove this please? next doesnt support node 22 and is going to throw errors

2024-11-19 12:48 UTC, TheGreatGildo reviewed
lgtm

2024-11-19 12:49 UTC, TheGreatGildo approved these changes

2024-11-19 12:50 UTC, merged